name: SuperVanish
main: ErkamKahriman\Vanish\Vanish
version: 2.2
author: ErkamKahriman
api: 3.0.0
commands:
  supervanish:
    description: "Vanish yourself"
    aliases: [sv]
permissions:
  supervanish.spectate:
    description: "Vanish use perm"
    default: op